### PR TITLE
Modified generate_tfrecord.py to use with TF2

### PR DESCRIPTION
**Pull request by shanejohnpaul**

### CODE REVIEW

**Comment by douglasrizzo** [comment]
Thanks for the contribution. Can you tell me if TFRecords generated with one version of TensorFlow work with the other?

**Comment by shanejohnpaul** [comment]
TFRecords should be the same regardless of the version. In fact, the changes are using TF1's functions. Still, I'm not completely sure though.

I have completely switched over to Tensorflow v2. And some of these functions are moved to different locations in TF2. And that's all the changes I made. 

I think the same exact code will work with TF1 too since it also has these functions (tf.compat.v1 and tf.io.gfile). I haven't checked `generate_yolo_txt.py` and `generate_train_eval.py` for compatibility with TF1.

**Comment by douglasrizzo** [comment]
I believe only `generate_tfrecord.py` actually uses TensorFlow. I will have a project with some object detection coming soon. I'll test your contribution then and merge as soon as possible.

**Comment by shanejohnpaul** [comment]
Nice!

**Pull request merged**
